# Generated by Django 5.1.2 on 2024-10-11 16:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Date of Creation"
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Date of expiration",
                    ),
                ),
                (
                    "user_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="Description"),
                ),
                ("priority", models.IntegerField(verbose_name="Priority")),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Date of Creation"
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Date of expiration",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.project",
                        verbose_name="Project",
                    ),
                ),
            ],
        ),
    ]
